### PR TITLE
Updating to WF 10, new JMS config and 1.2.x series

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@secondsun @yvnicolas mind giving this a try?

NOTE: I will tag before we merge this, so that we have a TAG, with 1.1.x series and WF9

**Comment by yvnicolas** [comment]
@matzew launched it successfully this morning on a new Database, post built of the 2 images aerogear/willdfly and the final one.

**Comment by matzew** [comment]
DO NOT MERGE YET!

**Comment by matzew** [comment]
LANDED!

**Pull request closed without merging**
