### PR TITLE
Adding 1.1.2(.Final) support

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@yvnicolas updated to 1.1.2 

yes, there is a version foo :) will be fixed in 1.1.3.Final :)

Note: that DEV is not yet working, since does not run on WF 10. Will look at WF 10 for 1.1.3

**Comment by matzew** [comment]
the keycloak version we use on 1.1.x branch seems to be incompatible w/ WF 10

**Comment by yvnicolas** [comment]
@matzew I would recommend to use $UPSVER in line 12 in the directory path. Slight difference in naming convention between 1.1.1 and 1.1.2 : Final is in the directory path for both but the tar dist archive name has final in it for 1.1.1 and not for 1.1.2.

**Comment by secondsun** [comment]
Just built it and ran it with the docker-compose script in the main project.  Seems to work fine.

**Comment by matzew** [comment]
@yvnicolas ha! yes, good call! Will update it, thanks!

@secondsun thanks for testing! :)

:tada:

**Pull request merged**
