### PR TITLE
UPS 1.1.0 - beta.2 update

### PR DESCRIPTION
**Pull request by matzew**
* using latest of UPS 1.1.0 (beta.2)
* using full profile (required due to JMS)
* adding newly required Keycloak DS

### CODE REVIEW

**Comment by matzew** [comment]
@abstractj @sebastienblanc mind to review / test the two changed docker images ?

**Comment by matzew** [comment]
@danielpassos mind to do a quick test and merge it ?

**Comment by danielpassos** [comment]
Not sure if it is related with it but I'm geeting

```
sed: can't read /etc/sudoers: No such file or directory
INFO[1071] The command [/bin/sh -c sed -i 's/.*requiretty$/#Defaults requiretty/' /etc/sudoers] returned a non-zero code: 2
```

**Comment by matzew** [comment]
@danielpassos I am getting the same (now)...

Perhaps @abstractj knows more ? 

I just did comment it out - 

than I got a different error on the `certificate.sh` script (`sudo: command not found`).
Running them w/o 'sudo' (in `certificate.sh`) made it build locally.

I *think* there is perhaps a change in the layers above aerogear/wildfly (e.g. jboss/wildfly)? 

will check some more ...

**Comment by matzew** [comment]
Closing this PR - I am changing the FILES to also use MySQL

**Pull request closed without merging**
