### PR TITLE
1.1.3.Final location

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@yvnicolas mind giving this a quick shot too ?

**Comment by yvnicolas** [comment]
will do end of afternoon

**Comment by yvnicolas** [comment]
Regular image build fine but I was not able to start the server. Linked it with 2 existing databases running fine on 1.1.2. Bleow is start trace from server. 
```
 versions without notice.
18:10:34,047 INFO  [org.jboss.as.jpa] (MSC service thread 1-7) WFLYJPA0002: Read persistence.xml for unifiedpush-default
18:10:34,083 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC000001: Failed to start service jboss.deployment.unit."unifiedpush-server-wildfly.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."unifiedpush-server-wildfly.war".PARSE: WFLYSRV0153: Failed to process phase PARSE of deployment "unifiedpush-server-wildfly.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYMSGAMQ0055: Could not parse file /opt/jboss/wildfly/standalone/tmp/vfs/temp/temp7500dc8f60095553/content-621a8983a69cb04/WEB-INF/hornetq-jms.xml
	at org.wildfly.extension.messaging.activemq.deployment.MessagingXmlParsingDeploymentUnitProcessor.deploy(MessagingXmlParsingDeploymentUnitProcessor.java:98)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	... 5 more
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYMSGAMQ0055: Could not parse file /opt/jboss/wildfly/standalone/tmp/vfs/temp/temp7500dc8f60095553/content-621a8983a69cb04/WEB-INF/hornetq-jms.xml
	at org.wildfly.extension.messaging.activemq.deployment.MessagingXmlParsingDeploymentUnitProcessor.deploy(MessagingXmlParsingDeploymentUnitProcessor.java:95)
	... 6 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[20,1]
Message: Unexpected element '{urn:jboss:messaging-deployment:1.0}messaging-deployment'
	at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:108)
	at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69)
	at org.wildfly.extension.messaging.activemq.deployment.MessagingXmlParsingDeploymentUnitProcessor.deploy(MessagingXmlParsingDeploymentUnitProcessor.java:89)
	... 6 more

18:10:35,837 INFO  [org.keycloak.services.resources.KeycloakApplication] (ServerService Thread Pool -- 66) Load config from vfs:/content/unifiedpush-auth-server.war/WEB-INF/classes/META-INF/keycloak-server.json
18:10:37,229 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 66) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2209)
	at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:299)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:240)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to connect to database
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:184)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lazyInit(DefaultJpaConnectionProviderFactory.java:130)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:35)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:25)
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:99)
	at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:34)
	at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:16)
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:99)
	at org.keycloak.models.cache.DefaultCacheRealmProvider.getDelegate(DefaultCacheRealmProvider.java:70)
	at org.keycloak.models.cache.DefaultCacheRealmProvider.getRealm(DefaultCacheRealmProvider.java:163)
	at org.keycloak.services.managers.ApplianceBootstrap.bootstrap(ApplianceBootstrap.java:40)
	at org.keycloak.services.managers.ApplianceBootstrap.bootstrap(ApplianceBootstrap.java:31)
	at org.keycloak.services.resources.KeycloakApplication.setupDefaultRealm(KeycloakApplication.java:157)
	at org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication.setupDefaultRealm(UpsKeycloakApplication.java:40)
	at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:87)
	at org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication.<init>(UpsKeycloakApplication.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
	... 19 more
Caused by: javax.naming.NameNotFoundException: datasources/KeycloakDS -- service jboss.naming.context.java.jboss.datasources.KeycloakDS
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:106)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:207)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:184)
	at org.jboss.as.naming.InitialContext$DefaultInitialContext.lookup(InitialContext.java:237)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:193)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:189)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:177)
	... 39 more

18:10:37,257 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "unifiedpush-auth-server.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./auth" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
    Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
    Caused by: java.lang.RuntimeException: Failed to connect to database
    Caused by: javax.naming.NameNotFoundException: datasources/KeycloakDS -- service jboss.naming.context.java.jboss.datasources.KeycloakDS"}}
18:10:37,264 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "unifiedpush-server-wildfly.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"unifiedpush-server-wildfly.war\".PARSE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"unifiedpush-server-wildfly.war\".PARSE: WFLYSRV0153: Failed to process phase PARSE of deployment \"unifiedpush-server-wildfly.war\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYMSGAMQ0055: Could not parse file /opt/jboss/wildfly/standalone/tmp/vfs/temp/temp7500dc8f60095553/content-621a8983a69cb04/WEB-INF/hornetq-jms.xml
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYMSGAMQ0055: Could not parse file /opt/jboss/wildfly/standalone/tmp/vfs/temp/temp7500dc8f60095553/content-621a8983a69cb04/WEB-INF/hornetq-jms.xml
    Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[20,1]
Message: Unexpected element '{urn:jboss:messaging-deployment:1.0}messaging-deployment'"}}
18:10:37,267 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "KeycloakDS")
]) - failure description: "WFLYCTL0211: Cannot resolve expression 'jdbc:mysql://${env.KEYCLOAK_PORT_3306_TCP_ADDR}:${env.KEYCLOAK_PORT_3306_TCP_PORT}/${env.KEYCLOAK_ENV_MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF-8'"
18:10:37,481 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 37) WFLYSRV0010: Deployed "unifiedpush-server-wildfly.war" (runtime-name : "unifiedpush-server-wildfly.war")
18:10:37,487 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 37) WFLYSRV0010: Deployed "unifiedpush-auth-server.war" (runtime-name : "unifiedpush-auth-server.war")
18:10:37,494 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
      service jboss.deployment.unit."unifiedpush-server-wildfly.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."unifiedpush-server-wildfly.war".PARSE: WFLYSRV0153: Failed to process phase PARSE of deployment "unifiedpush-server-wildfly.war"

18:10:38,459 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
18:10:38,460 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
18:10:38,462 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 10.0.0.Final (WildFly Core 2.0.10.Final) started (with errors) in 42547ms - Started 445 of 741 services (3 services failed or missing dependencies, 439 services are lazy, passive or on-demand)
```

**Comment by matzew** [comment]
there is something wrong w/ the damn docker link for the DBs:

 jdbc:mysql://${env.KEYCLOAK_PORT_3306_TCP_ADDR}:${env.
KEYCLOAK_PORT_3306_TCP

On Thu, May 12, 2016 at 8:15 PM, yvnicolas <notifications@github.com> wrote:

> Regular image build fine but I was not able to start the server. Linked it
> with 2 existing databases running fine on 1.1.2. Bleow is start trace from
> server.
>
>  versions without notice.
> 18:10:34,047 INFO  [org.jboss.as.jpa] (MSC service thread 1-7) WFLYJPA0002: Read persistence.xml for unifiedpush-default
> 18:10:34,083 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC000001: Failed to start service jboss.deployment.unit."unifiedpush-server-wildfly.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."unifiedpush-server-wildfly.war".PARSE: WFLYSRV0153: Failed to process phase PARSE of deployment "unifiedpush-server-wildfly.war"
>     at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
>     at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
>     at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYMSGAMQ0055: Could not parse file /opt/jboss/wildfly/standalone/tmp/vfs/temp/temp7500dc8f60095553/content-621a8983a69cb04/WEB-INF/hornetq-jms.xml
>     at org.wildfly.extension.messaging.activemq.deployment.MessagingXmlParsingDeploymentUnitProcessor.deploy(MessagingXmlParsingDeploymentUnitProcessor.java:98)
>     at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
>     ... 5 more
> Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYMSGAMQ0055: Could not parse file /opt/jboss/wildfly/standalone/tmp/vfs/temp/temp7500dc8f60095553/content-621a8983a69cb04/WEB-INF/hornetq-jms.xml
>     at org.wildfly.extension.messaging.activemq.deployment.MessagingXmlParsingDeploymentUnitProcessor.deploy(MessagingXmlParsingDeploymentUnitProcessor.java:95)
>     ... 6 more
> Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[20,1]
> Message: Unexpected element '{urn:jboss:messaging-deployment:1.0}messaging-deployment'
>     at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:108)
>     at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69)
>     at org.wildfly.extension.messaging.activemq.deployment.MessagingXmlParsingDeploymentUnitProcessor.deploy(MessagingXmlParsingDeploymentUnitProcessor.java:89)
>     ... 6 more
>
> 18:10:35,837 INFO  [org.keycloak.services.resources.KeycloakApplication] (ServerService Thread Pool -- 66) Load config from vfs:/content/unifiedpush-auth-server.war/WEB-INF/classes/META-INF/keycloak-server.json
> 18:10:37,229 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 66) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
>     at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
>     at org.jboss.threads.JBossThread.run(JBossThread.java:320)
> Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
>     at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
>     at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2209)
>     at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:299)
>     at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:240)
>     at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
>     at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
>     at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
>     at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
>     at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
>     at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
>     at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
>     at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
>     at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
>     at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
>     ... 6 more
> Caused by: java.lang.RuntimeException: Failed to connect to database
>     at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:184)
>     at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lazyInit(DefaultJpaConnectionProviderFactory.java:130)
>     at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:35)
>     at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:25)
>     at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:99)
>     at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:34)
>     at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:16)
>     at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:99)
>     at org.keycloak.models.cache.DefaultCacheRealmProvider.getDelegate(DefaultCacheRealmProvider.java:70)
>     at org.keycloak.models.cache.DefaultCacheRealmProvider.getRealm(DefaultCacheRealmProvider.java:163)
>     at org.keycloak.services.managers.ApplianceBootstrap.bootstrap(ApplianceBootstrap.java:40)
>     at org.keycloak.services.managers.ApplianceBootstrap.bootstrap(ApplianceBootstrap.java:31)
>     at org.keycloak.services.resources.KeycloakApplication.setupDefaultRealm(KeycloakApplication.java:157)
>     at org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication.setupDefaultRealm(UpsKeycloakApplication.java:40)
>     at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:87)
>     at org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication.<init>(UpsKeycloakApplication.java:35)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>     at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
>     ... 19 more
> Caused by: javax.naming.NameNotFoundException: datasources/KeycloakDS -- service jboss.naming.context.java.jboss.datasources.KeycloakDS
>     at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:106)
>     at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:207)
>     at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:184)
>     at org.jboss.as.naming.InitialContext$DefaultInitialContext.lookup(InitialContext.java:237)
>     at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:193)
>     at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:189)
>     at javax.naming.InitialContext.lookup(InitialContext.java:417)
>     at javax.naming.InitialContext.lookup(InitialContext.java:417)
>     at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:177)
>     ... 39 more
>
> 18:10:37,257 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "unifiedpush-auth-server.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./auth" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
>     Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
>     Caused by: java.lang.RuntimeException: Failed to connect to database
>     Caused by: javax.naming.NameNotFoundException: datasources/KeycloakDS -- service jboss.naming.context.java.jboss.datasources.KeycloakDS"}}
> 18:10:37,264 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "unifiedpush-server-wildfly.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"unifiedpush-server-wildfly.war\".PARSE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"unifiedpush-server-wildfly.war\".PARSE: WFLYSRV0153: Failed to process phase PARSE of deployment \"unifiedpush-server-wildfly.war\"
>     Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYMSGAMQ0055: Could not parse file /opt/jboss/wildfly/standalone/tmp/vfs/temp/temp7500dc8f60095553/content-621a8983a69cb04/WEB-INF/hornetq-jms.xml
>     Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYMSGAMQ0055: Could not parse file /opt/jboss/wildfly/standalone/tmp/vfs/temp/temp7500dc8f60095553/content-621a8983a69cb04/WEB-INF/hornetq-jms.xml
>     Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[20,1]
> Message: Unexpected element '{urn:jboss:messaging-deployment:1.0}messaging-deployment'"}}
> 18:10:37,267 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
>     ("subsystem" => "datasources"),
>     ("data-source" => "KeycloakDS")
> ]) - failure description: "WFLYCTL0211: Cannot resolve expression 'jdbc:mysql://${env.KEYCLOAK_PORT_3306_TCP_ADDR}:${env.KEYCLOAK_PORT_3306_TCP_PORT}/${env.KEYCLOAK_ENV_MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF-8'"
> 18:10:37,481 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 37) WFLYSRV0010: Deployed "unifiedpush-server-wildfly.war" (runtime-name : "unifiedpush-server-wildfly.war")
> 18:10:37,487 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 37) WFLYSRV0010: Deployed "unifiedpush-auth-server.war" (runtime-name : "unifiedpush-auth-server.war")
> 18:10:37,494 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
> WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.jboss.aerogear.unifiedpush.keycloak.UpsKeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
>       service jboss.deployment.unit."unifiedpush-server-wildfly.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."unifiedpush-server-wildfly.war".PARSE: WFLYSRV0153: Failed to process phase PARSE of deployment "unifiedpush-server-wildfly.war"
>
> 18:10:38,459 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
> 18:10:38,460 <http://127.0.0.1:9990/management18:10:38,460> INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
> 18:10:38,462 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 10.0.0.Final (WildFly Core 2.0.10.Final) started (with errors) in 42547ms - Started 445 of 741 services (3 services failed or missing dependencies, 439 services are lazy, passive or on-demand)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/dockerfiles/pull/17#issuecomment-218841082>
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by yvnicolas** [comment]
My fault, did it to quickly leaving work, I made a typo in launching the container with the link, forgot the y in keycloak. Probable cause. Can not look at it tonight but will do it first thing in the morning tomorrow

**Comment by yvnicolas** [comment]
First tried it again with right spelling on my existing databases, got the following exception,  [full trace attached](https://github.com/aerogear/dockerfiles/files/262575/20160513tracedockerups113.txt)
```
aused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'userfedera0_.RealmEntity_ID' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
```

Then tried it on new containers. Got following error from liquibase process
```
Starting Liquibase migration
Unexpected error running Liquibase: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
```
Tried it twice to make sure I had no spelling mistakes again, everything seems fine...

**Comment by matzew** [comment]
@yvnicolas I think you are mixing something here, the 1.1.x is not supposed to run on WF-10.
```
 WildFly Full 10.0.0.Final
```

the stack above is from Keycloak, and between 1.1.x and 1.2.0 there are different KC versions, I think that should work :) Perhaps there is a KC migration bug?  Will talk with them

**Comment by yvnicolas** [comment]
You are right, I did not do the full process and did not recreate the wildfly image. Using WF9 works fine with my existing database. I still have the Liquibase migration error starting on brand new databases.

**Comment by matzew** [comment]
ah, ok - will merge this.

Can you file a JIRA for the migration issue on the master files? I'd like
to get that sorted out rather soon.

Thanks

On Fri, May 13, 2016 at 7:22 AM, yvnicolas <notifications@github.com> wrote:

> You are right, I did not do the full process and did not recreate the
> wildfly image. Using WF9 works fine with my existing database. I still have
> the Liquibase migration error starting on brand new databases.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/dockerfiles/pull/17#issuecomment-218954619>
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by yvnicolas** [comment]
Filed the Jira. In the process of adding it relaunched it with my void db containers, did not get the error. My guess is it is actually a timing problem that I have seen with docker db containers linked together. I might have launched the ups container too quickly after the db ones, the db containers are not yet properly started and no data base connections can be started.

Current status is : the server is up but when I try to connect it, I get 
```
Starting Liquibase migration
Unexpected error running Liquibase: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
```

I will try and do some more tests later today and update the Jira accordingly

PS : this is the first Jira I filed, I would welcome any recommendations on best practices.

**Comment by yvnicolas** [comment]
If the timing hypothesis is the right one, the best way to prevent it will be to add a waiting instructions in the entry point of the docker container. I ll take care of submitting a pull request on this one once my tests are done.

**Pull request merged**
